### ISSUE TITLE
Update other packages to `pyproject.toml` remove `requirements-dector` dependency

### ISSUE THREAD

**Issue by ketiltrout** [chime-experiment/mkchimeenv#10]
To follow-up on #9 here are the CHIME packages that we would need to convert to `pyproject.toml`:

Radiocosmology packages (most of these involve cython)
* [x] [caput](https://github.com/radiocosmology/caput) radiocosmology/caput#272
* [x] [cora](https://github.com/radiocosmology/cora) radiocosmology/cora#58
* [x] [driftscan](https://github.com/radiocosmology/driftscan) radiocosmology/driftscan#119
* [x] [draco](https://github.com/radiocosmology/draco) radiocosmology/draco#283

chime-experiment packages
* [x] [chimedb.core](https://github.com/chime-experiment/chimedb) https://github.com/chime-experiment/chimedb/pull/44
* [x] [chimedb.config](https://github.com/chime-experiment/chimedb_config) https://github.com/chime-experiment/chimedb_config/pull/6
* [x] [chimedb.dataflag](https://github.com/chime-experiment/chimedb_dataflag) https://github.com/chime-experiment/chimedb_dataflag/pull/19
* [X] [chimedb.dataset](https://github.com/chime-experiment/chimedb_dataset)
* [X] [chimedb.data_index](https://github.com/chime-experiment/chimedb_di)
* [X] [ch_epehm](https://github.com/chime-experiment/ch_ephem)  ***new***
* [x] [ch_pipeline](https://github.com/chime-experiment/ch_pipeline) https://github.com/chime-experiment/ch_pipeline/pull/264
* [x] [ch_util](https://github.com/chime-experiment/ch_util) https://github.com/chime-experiment/ch_util/pull/78
